export const FETCH_SIGNIN_REQUEST = "FETCH_SIGNIN_REQUEST";
export const FETCH_SIGNIN_SUCCESS = "FETCH_SIGNIN_SUCCESS";
export const FETCH_SIGNIN_FAILURE = "FETCH_SIGNIN_FAILURE";

export const FETCH_SIGNUP_REQUEST = "FETCH_SIGNUP_REQUEST";
export const FETCH_SIGNUP_SUCCESS = "FETCH_SIGNUP_SUCCESS";
export const FETCH_SIGNUP_FAILURE = "FETCH_SIGNUP_FAILURE";

export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const USER_LOGOUT = "USER_LOGOUT";