export const FETCH_MEALS_REQUEST = "FETCH_MEALS_REQUEST";
export const FETCH_MEALS_SUCCESS = "FETCH_MEALS_SUCCESS";
export const FETCH_MEALS_FAILURE = "FETCH_MEALS_FAILURE";

export const ADD_MEALS_REQUEST = "ADD_MEALS_REQUEST";
export const ADD_MEALS_SUCCESS = "ADD_MEALS_SUCCESS";
export const ADD_MEALS_FAILURE = "ADD_MEALS_FAILURE";

export const REMOVE_MEALS_REQUEST = "REMOVE_MEALS_REQUEST";
export const REMOVE_MEALS_SUCCESS = "REMOVE_MEALS_SUCCESS";
export const REMOVE_MEALS_FAILURE = "REMOVE_MEALS_FAILURE";

export const UPDATE_MEALS_REQUEST = "UPDATE_MEALS_REQUEST";
export const UPDATE_MEALS_SUCCESS = "UPDATE_MEALS_SUCCESS";
export const UPDATE_MEALS_FAILURE = "UPDATE_MEALS_FAILURE";