export const FETCH_MENU_REQUEST = "FETCH_MENU_REQUEST";
export const FETCH_MENU_SUCCESS = "FETCH_MENU_SUCCESS";
export const FETCH_MENU_FAILURE = "FETCH_MENU_FAILURE";

export const SETUP_MENU_REQUEST = "SETUP_MENU_REQUEST";
export const SETUP_MENU_SUCCESS = "SETUP_MENU_SUCCESS";
export const SETUP_MENU_FAILURE = "SETUP_MENU_FAILURE";