export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILURE = "FETCH_ORDERS_FAILURE";

export const ADD_ORDERS_REQUEST = "ADD_ORDERS_REQUEST";
export const ADD_ORDERS_SUCCESS = "ADD_ORDERS_SUCCESS";
export const ADD_ORDERS_FAILURE = "ADD_ORDERS_FAILURE";

export const REMOVE_ORDERS_REQUEST = "REMOVE_ORDERS_REQUEST";
export const REMOVE_ORDERS_SUCCESS = "REMOVE_ORDERS_SUCCESS";
export const REMOVE_ORDERS_FAILURE = "REMOVE_ORDERS_FAILURE";

export const UPDATE_ORDERS_REQUEST = "UPDATE_ORDERS_REQUEST";
export const UPDATE_ORDERS_SUCCESS = "UPDATE_ORDERS_SUCCESS";
export const UPDATE_ORDERS_FAILURE = "UPDATE_ORDERS_FAILURE";